[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

# decorations = "Buttonless"

opacity = 0.8
blur = true

[font]
normal.family = "FiraCode Nerd Font Mono"
# normal.family = "MonaspiceNe Nerd Font"

# size = 10
size = 13

offset.x = 1
offset.y = 5

# Theme imports - these will be automatically switched by the theme switcher
[general]
import = [
  "~/.config/alacritty/current-theme.toml"
]

# Alternative themes you can use:
# Light themes:
# - "~/.config/alacritty/themes/themes/one_light.toml"
# - "~/.config/alacritty/themes/themes/github_light.toml" 
# - "~/.config/alacritty/themes/themes/pencil_light.toml"
# - "~/.config/alacritty/themes/themes/tomorrow.toml"

# Dark themes:
# - "~/.config/alacritty/themes/themes/dracula.toml"
# - "~/.config/alacritty/themes/themes/tokyo_night.toml"
# - "~/.config/alacritty/themes/themes/one_dark.toml"

# Send ESC+<number> when pressing Cmd+<number>
[[keyboard.bindings]]
key = "Key1"
mods = "Command"
chars = "\u001b1"
[[keyboard.bindings]]
key = "Key2"
mods = "Command"
chars = "\u001b2"
[[keyboard.bindings]]
key = "Key3"
mods = "Command"
chars = "\u001b3"
[[keyboard.bindings]]
key = "Key4"
mods = "Command"
chars = "\u001b4"
[[keyboard.bindings]]
key = "Key5"
mods = "Command"
chars = "\u001b5"
[[keyboard.bindings]]
key = "Key6"
mods = "Command"
chars = "\u001b6"
[[keyboard.bindings]]
key = "Key7"
mods = "Command"
chars = "\u001b7"
[[keyboard.bindings]]
key = "Key8"
mods = "Command"
chars = "\u001b8"
[[keyboard.bindings]]
key = "Key9"
mods = "Command"
chars = "\u001b9"
[[keyboard.bindings]]
key = "Key0"
mods = "Command"
chars = "\u001b0"

[[keyboard.bindings]]
key = "N"
mods = "Command"
chars = "\u001bn"

[[keyboard.bindings]]
key = "W"
mods = "Command"
chars = "\u001bw"

[[keyboard.bindings]]
key = "H"
mods = "Command"
chars = "\u001bh"

[[keyboard.bindings]]
key = "L"
mods = "Command"
chars = "\u001bl"

# Cmd+Shift+1 -> ESC + "a"
[[keyboard.bindings]]
key = "A"
mods = "Command|Shift"
chars = "\u001ba"

# Cmd+Shift+2 -> ESC + "b"
[[keyboard.bindings]]
key = "B"
mods = "Command|Shift"
chars = "\u001bb"

# Cmd+Shift+3 -> ESC + "m"
[[keyboard.bindings]]
key = "M"
mods = "Command|Shift"
chars = "\u001bm"

# Key bindings for manual theme switching
[[keyboard.bindings]]
key = "F1"
mods = "Command"
command = { program = "/bin/sh", args = ["-c", "~/.config/scripts/theme-switcher.sh"] }

[[keyboard.bindings]]
key = "F2"
mods = "Command"
command = { program = "/bin/sh", args = ["-c", "echo 'light' > ~/.current_theme && ~/.config/scripts/theme-switcher.sh"] }

[[keyboard.bindings]]
key = "F3"
mods = "Command" 
command = { program = "/bin/sh", args = ["-c", "echo 'dark' > ~/.current_theme && ~/.config/scripts/theme-switcher.sh"] }

# Cmd + Shift + 1
[[keyboard.bindings]]
key = "Key1"
mods = "Command|Shift"
action = "SelectTab1"

# Cmd + Shift + 2
[[keyboard.bindings]]
key = "Key2"
mods = "Command|Shift"
action = "SelectTab2"

# Cmd + Shift + 3
[[keyboard.bindings]]
key = "Key3"
mods = "Command|Shift"
action = "SelectTab3"

# Cmd + Shift + 4
[[keyboard.bindings]]
key = "Key4"
mods = "Command|Shift"
action = "SelectTab4"

# Cmd + Shift + 5
[[keyboard.bindings]]
key = "Key5"
mods = "Command|Shift"
action = "SelectTab5"

# Cmd + Shift + 6
[[keyboard.bindings]]
key = "Key6"
mods = "Command|Shift"
action = "SelectTab6"

# Cmd + Shift + 7
[[keyboard.bindings]]
key = "Key7"
mods = "Command|Shift"
action = "SelectTab7"

# Cmd + Shift + 8
[[keyboard.bindings]]
key = "Key8"
mods = "Command|Shift"
action = "SelectTab8"

# Cmd + Shift + 9
[[keyboard.bindings]]
key = "Key9"
mods = "Command|Shift"
action = "SelectTab9"
